<?php

return [
    'Doctor Master' => 'DocMas',
    'Doctor Timing' => 'DocTim',
    'Fees Master' => 'FeesMas',
    'Test Master' => 'TestMas',
    'Group Test Master' => 'GroupTMas',
    'Profile Master' => 'ProfMas',
    'Lab Master' => 'LabMas',
    'Room Master' => 'RoomMas',
    'Radio Therapy Master' => 'RadTherMas',
    'User Access' => 'UserAcc',
    'User Master' => 'UserMas',
    'Appointments' => 'appts',
    'Medical Observation' => 'MedObs',
    'Patient Registration' => 'Reg',
    'Patient List' => 'List',
    'Patient Update' => 'PtUpd',
    'PDF Upload' => 'UpPDF',
    'OP Registration' => 'OPReg',
    'Prescription' => 'Presc',
    // 'Patient Image'=>'OPIm',
    // 'Oncologist Sheet'=>'RadioOnc',
    // 'Physicist Sheet'=>'RadioPhy',
    // 'Technologist Sheet'=>'RadioTech',
    'OP Billing' => 'OPBill',
    // 'OP Feedback' => 'OPFBK',
    'IP Billing' => 'IPBill',
    'IP Advance' => 'IPAdv',
    // 'Purchase' => 'InvItPur',
    // 'Indent Form' => 'InvInd',
    // 'Reminder Form' => 'InvRem',
    'Admission' => 'IPAdm',
    'Treatment' => 'IPTre',
    'History' => 'IPHis',
    'Ward Status' => 'WardStat',
    'Ward Shifting' => 'WardShift',
    'XRay Upload' => 'XRay',
    'Discharge' => 'IPDis',
    'OP Lab' => 'OPL',
    'IP Lab' => 'IPL',
    'Reports' => 'Rep',
    'Update' => 'update',
    'Delete' => 'delete'
        // 'Chart Update'=>'ChUp',
        // 'Data Backup'=>'BackUp'
];
